"""exp41: Compute FITD Table 7 per-seed mean±std from per_sample predictions.

Source: results/per_sample_predictions/fitd_ood_per_sample.json
  - Generated by exp35_cross_seed_ensemble.py using plan_002 production checkpoints
  - 9class: plan_002 (DeBERTa multitask + GRU)
  - vanilla: pretrained DeBERTa + plan_002 baseline GRU
  - Evaluated on 80 FITD attack + 38 IID test benign = 118 samples

Output: results/exp41_fitd_table7_perseed.json
"""
import json
import numpy as np
from pathlib import Path
from sklearn.metrics import f1_score

PROJ = Path(".")
PER_SAMPLE = PROJ / "results/per_sample_predictions/fitd_ood_per_sample.json"
OUT = PROJ / "results/exp41_fitd_table7_perseed.json"

TABLE7_CURRENT = {
    "9class": {"K1": 1.000, "K2": 1.000, "Full": 1.000},
    "vanilla": {"K1": 0.990, "K2": 1.000, "Full": 1.000},
}

K_MAP = {"K1": "k1", "K2": "k2", "Full": "full"}
SEEDS = ["42", "123", "456"]

with open(PER_SAMPLE) as f:
    data = json.load(f)

labels = data["labels"]
preds = data["preds"]

results = {}
for variant, ps_key in [("9class", "9class"), ("vanilla", "vanilla")]:
    results[variant] = {}
    for k_display, k_raw in K_MAP.items():
        seed_f1s = []
        for s in SEEDS:
            p = preds[ps_key][s][k_raw]
            f1 = f1_score(labels, p, average="macro")
            seed_f1s.append(round(f1, 6))
        mean = float(np.mean(seed_f1s))
        std = float(np.std(seed_f1s, ddof=0))
        results[variant][k_display] = {
            "seeds": {int(s): v for s, v in zip(SEEDS, seed_f1s)},
            "mean": round(mean, 6),
            "std": round(std, 6),
        }

output = {
    "description": "FITD OOD per-seed F1-macro for Table 7 (tab:full_prefix)",
    "source": "results/per_sample_predictions/fitd_ood_per_sample.json",
    "checkpoints": "plan_002 (from checkpoints_archive via exp35)",
    "n_attack": 80,
    "n_benign": 38,
    "n_total": 118,
    "metric": "F1-macro",
    "std_ddof": 0,
    "results": results,
}

with open(OUT, "w") as f:
    json.dump(output, f, indent=2)

print("=" * 70)
print("FITD Table 7 per-seed results (F1-macro, population std ddof=0)")
print("=" * 70)
print(f"Data: 80 attack + 38 benign = 118 samples")
print(f"Checkpoints: plan_002 (production)")
print()

for variant in ["9class", "vanilla"]:
    print(f"--- {variant} ---")
    for k in ["K1", "K2", "Full"]:
        r = results[variant][k]
        seeds = [r["seeds"][s] for s in [42, 123, 456]]
        print(f"  {k}: {r['mean']:.3f}±{r['std']:.3f}  seeds={[f'{v:.4f}' for v in seeds]}")

        if variant in TABLE7_CURRENT and k in TABLE7_CURRENT[variant]:
            table_val = TABLE7_CURRENT[variant][k]
            delta = abs(r["mean"] - table_val)
            if delta > 0.005:
                print(f"    ⚠ DEVIATION: table has {table_val:.3f}, mean is {r['mean']:.3f} (Δ={delta:.3f})")
                print(f"      Reason: table used seed 42 only ({r['seeds'][42]:.3f})")
    print()

print("LaTeX (K=3, K=5 remain --):")
for variant, label in [("9class", "9-class (ours)"), ("vanilla", "Vanilla DeBERTa")]:
    r = results[variant]
    parts = []
    for k in ["K1", "K2"]:
        m, s = r[k]["mean"], r[k]["std"]
        if s < 0.0005:
            parts.append(f"{m:.3f}")
        else:
            parts.append(f"{m:.3f}$\\pm${s:.3f}")
    parts.append("--")
    parts.append("--")
    k = "Full"
    m, s = r[k]["mean"], r[k]["std"]
    if s < 0.0005:
        parts.append(f"{m:.3f}")
    else:
        parts.append(f"{m:.3f}$\\pm${s:.3f}")
    print(f"{label} & {' & '.join(parts)} \\\\")

print(f"\nSaved: {OUT}")
